### ISSUE TITLE
Mocking event emitters

### ISSUE THREAD

**Issue by soggie** [arunoda/nodemock#10]
How do I mock event emitters? In my current project I use a factory pattern to achieve dependency injection on all modules (every module has a make() function that is basically a constructor injection thingy), and I have no trouble mocking NodeJS core API but have no idea how to mock event emitters (other than writing my own).

How does nodemock do this?

**Comment by arunoda** [comment]
nodemock works great with dependency injection. But with the core modules and other it'll be little tricky.
So there is no such direct solution in nodemock and it does only mocking.
Mocking event emitters in very tricky.

But You can it as follows.
//Start of the Test

var event = require('event');
var oldOne = event.EventEmitter;
event.EventEmitter = YourVersion;

//Do the test

event.EventEmitter = oldOne;

**Comment by soggie** [comment]
I guess that would work, although after posting that I did a double take and figured trying to mock a emitter is kind of useless anyway since emitters are isolated code by themselves. Feel free to close this issue. :p

**Comment by arunoda** [comment]
It just closed :P
