### ISSUE TITLE
fail() throws exception on assertThrows when method was not called

### ISSUE THREAD

**Issue by ebunders** [arunoda/nodemock#12]
When you add a method to the mock that you explicitely don't want to be called, but afterwards call mock.assertThrows, becouse there was another method that did have to be called, fail() throws an error, even if that method was not called. 

I wrote a little test to illustrate the problem (it fails):

exports.testFailThrowsNoExceptionWhenNotCalled = function(test){
    var mock = nm.mock('test').fail();
    test.doesNotThrow(function() {
                // the method was not called so, no exception should be thrown
        mock.assertThrows();
    });
    test.done();  
}

**Comment by arunoda** [comment]
Yes that was an issue :)
I just fix that. Thanks for showing up.
And updated the NPM too. (version 0.2.15)

**Comment by ebunders** [comment]
no problem, 
cheers
