### ISSUE TITLE
BUG: leaking entry global var

### ISSUE THREAD

**Issue by jigargosar** [arunoda/nodemock#13]
- is the leak of entry var in global scope intentional, or is it a genuine mistake? I think its a mistake.

file: lib/nodemock.js, line 40, branch master.

entry = entries[method][index];
- thanks for this awesome lib.

**Comment by arunoda** [comment]
now it's fixed. actually it should be a local variable :)

**Comment by clarete** [comment]
Hi @arunoda, when will you release the 0.2.17 version? I just noticed it's not in npmjs.org yet. Thank you :)

**Comment by arunoda** [comment]
@clarete done

**Comment by clarete** [comment]
Wow! That was fast! Thank you :)
