### ISSUE TITLE
cannot assign a mocked function to a var

### ISSUE THREAD

**Issue by dominictarr** [arunoda/nodemock#6]
```
var nm = require('nodemock')

var m = nm.mock('foo').takes(10)
var foo = m.foo

foo(10)
```

this will throw

```
Error: Mock function 'foo()' is not defined
  at /home/dominic/source/dev/experiement/node_modules/nodemock/lib/nodemock.js:56:11
  at /home/dominic/source/dev/experiement/node_modules/nodemock/lib/nodemock.js:56:11
```

I use functions by them selves all the time, would be handy to be able to mock them. instead I have to do this:

   var foo = function () { m.foo.apply(m,[].slice.call(arguments) }

which is not as nice.

**Comment by arunoda** [comment]
try replace this line (http://goo.gl/7lUoD) with,

var self = this;
if(!self[method]) {

I cant add a commit now since i'm on the way.
cheers.

**Comment by arunoda** [comment]
fixed - https://github.com/arunoda/nodemock/tree/v0.2.10beta
