### ISSUE TITLE
mock.assert() does not throw... 

### ISSUE THREAD

**Issue by dominictarr** [arunoda/nodemock#7]
I would expect a function named `assert` to throw.

i'll get a pull request ready for this if you like, unless you have a particular reason for doing it this way?

**Comment by arunoda** [comment]
what are the benefits we are getting when we throw instead of just returning true or false ?

**Comment by dominictarr** [comment]
Well, if it doesn't throw the test framework will think that the test has
passed.

It needs to throw so that the framework knows there has been an error, and
it should go red.

**Comment by arunoda** [comment]
there has been hell a lot of tests has been written using this version of API (inside our private projects as well as others). So changing this would break tests.
But if you feel you really need it, we can have a seperate method like `assertThrows`. how about that?

**Comment by dominictarr** [comment]
that would be good enough!

cheers.

**Comment by arunoda** [comment]
I'll push the changes by tomorrow or send me a pull if you hurry :)

cheers

On Mon, Jun 27, 2011 at 1:42 AM, dominictarr <
reply@reply.github.com>wrote:

> that would be good enough!
> 
> cheers.
> 
> On Fri, Jun 24, 2011 at 9:51 PM, arunoda <
> reply@reply.github.com>wrote:
> 
> > there has been hell a lot of tests has been written using this version of
> > API (inside our private projects as well as others). So changing this
> > would
> > break tests.
> > But if you feel you really need it, we can have a seperate method like
> > `assertThrows`. how about that?
> > 
> > ## 
> > 
> > Reply to this email directly or view it on GitHub:
> > https://github.com/arunoda/nodemock/issues/7#issuecomment-1436983
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/arunoda/nodemock/issues/7#issuecomment-1442409

## 

Arunoda Susiripala
http://arunoda.com
http://twitter.com/arunoda

**Comment by arunoda** [comment]
now assertThrows() is added :)

**Comment by dominictarr** [comment]
awesome!
