### ISSUE TITLE
mock.assert() expects a method with .fail() to be called.

### ISSUE THREAD

**Issue by dominictarr** [arunoda/nodemock#8]
```
var y = nm.mock('doNotCall').fail()

y.assert()

//method call for: 'doNotCall()' with params: ) executed 0 times. (but excepted 1 times)
```

hmm, 0 is the correct amount of times to execute.

**Comment by arunoda** [comment]
this is a syntax error and I've not designed like this.
It should be like
nm.fail('doNotCall') instead nm.mock('doNotCall').fail();

but 2nd option also worthy.

On Thu, Jun 23, 2011 at 11:36 PM, dominictarr <
reply@reply.github.com>wrote:

> var y = nm.mock('doNotCall').fail()
> 
>    y.assert()
> 
>    //method call for: 'doNotCall()' with params: ) executed 0 times. (but
> excepted 1 times)
> 
> hmm, 0 is the correct amount of times to execute.
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/arunoda/nodemock/issues/8

## 

Arunoda Susiripala
http://arunoda.com
http://twitter.com/arunoda

**Comment by dominictarr** [comment]
ah, that is simpler!

thanks.

**Comment by arunoda** [comment]
great.

On Fri, Jun 24, 2011 at 6:57 AM, dominictarr <
reply@reply.github.com>wrote:

> ah, that is simpler!
> 
> thanks.
> 
> On Thu, Jun 23, 2011 at 4:54 PM, arunoda <
> reply@reply.github.com>wrote:
> 
> > this is a syntax error and I've not designed like this.
> > It should be like
> > nm.fail('doNotCall') instead nm.mock('doNotCall').fail();
> > 
> > but 2nd option also worthy.
> > 
> > On Thu, Jun 23, 2011 at 11:36 PM, dominictarr <
> > reply@reply.github.com>wrote:
> > 
> > > var y = nm.mock('doNotCall').fail()
> > > 
> > >    y.assert()
> > > 
> > >    //method call for: 'doNotCall()' with params: ) executed 0 times.
> > > (but
> > > excepted 1 times)
> > > 
> > > hmm, 0 is the correct amount of times to execute.
> > > 
> > > ## 
> > > 
> > > Reply to this email directly or view it on GitHub:
> > > https://github.com/arunoda/nodemock/issues/8
> > 
> > ## 
> > 
> > Arunoda Susiripala
> > http://arunoda.com
> > http://twitter.com/arunoda
> > 
> > ## 
> > 
> > Reply to this email directly or view it on GitHub:
> > https://github.com/arunoda/nodemock/issues/8#issuecomment-1429357
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/arunoda/nodemock/issues/8#issuecomment-1429697

## 

Arunoda Susiripala
http://arunoda.com
http://twitter.com/arunoda
